name: 'Setup Node.js'
description: 'Setup Node.js with caching and dependency installation'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Cache quality check artifacts
      uses: actions/cache@v4
      with:
        path: |
          .eslintcache
          tsconfig.tsbuildinfo
        key: ${{ runner.os }}-quality-${{ hashFiles('package.json', 'package-lock.json', 'eslint.config.*', 'tsconfig.json') }}
        restore-keys: |
          ${{ runner.os }}-quality-

    - name: Install dependencies
      shell: bash
      run: HUSKY=0 npm ci --no-audit --no-fund