name: Security Scan

on:
  schedule:
    - cron: '0 9 * * 1' # Weekly on Monday at 9 AM UTC
  pull_request:
    branches: [main, master, beta]

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Install dependencies
        run: HUSKY=0 npm ci --no-audit --no-fund

      - name: Run security audit
        run: npm run security:audit

      - name: Run dependency check
        run: npm run security:check

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          config-file: ./.github/codeql-config.yml

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
