name: Security Scan

on:
  schedule:
    - cron: '0 9 * * 1' # Weekly on Monday at 9 AM UTC
  pull_request:
    branches: [main, master, beta]

env:
  NODE_VERSION: '22.x'

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run security audit
        uses: ./.github/actions/security-audit

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          config-file: ./.github/codeql-config.yml

      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
