name: Test CI

on:
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'

jobs:
  test:
    name: Test CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run quality checks
        uses: ./.github/actions/quality-checks

      - name: Build and package
        uses: ./.github/actions/build-extension
        with:
          build-mode: production

      - name: Run security checks
        uses: ./.github/actions/security-audit
