name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'full'
        type: choice
        options:
          - 'full'
          - 'quality-only'
          - 'build-only'

env:
  NODE_VERSION: '22.x'

jobs:
  manual-test:
    name: Manual Test Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Quality checks
        if: contains(github.event.inputs.test_type, 'quality') || github.event.inputs.test_type == 'all'
        uses: ./.github/actions/quality-checks

      - name: Security audit
        if: contains(github.event.inputs.test_type, 'security') || github.event.inputs.test_type == 'all'
        uses: ./.github/actions/security-audit
        with:
          audit-level: 'moderate'
          fail-on-vulnerabilities: 'false'

      - name: Build extension
        if: contains(github.event.inputs.test_type, 'build') || github.event.inputs.test_type == 'all'
        uses: ./.github/actions/build-extension
        with:
          upload-artifacts: 'true'
          artifact-retention-days: '7'
