name: 'Quality Checks'
description: 'Run quality checks including linting, formatting, type checking, and tests'
runs:
  using: 'composite'
  steps:
    - name: Type check
      shell: bash
      run: npm run type-check

    - name: Lint code
      shell: bash
      run: npm run lint -- --cache

    - name: Check formatting
      shell: bash
      run: npm run format:check

    - name: Cache quality check artifacts
      uses: actions/cache@v4
      with:
        path: |
          coverage/
          .vitest/
          out/
        key: ${{ runner.os }}-quality-artifacts-${{ hashFiles('src/**/*.ts', 'tests/**/*.ts', 'vitest.config.*') }}
        restore-keys: |
          ${{ runner.os }}-quality-artifacts-

    - name: Run tests with coverage
      shell: bash
      run: npm run test:coverage
